language: php

matrix:
    fast_finish: true
    include:
        - php: 7.4

cache:
    directories:
        - $HOME/.composer/cache

before_script:
    - composer self-update
    - composer install --prefer-dist --no-progress

script:
    - composer check-cs
    - composer psalm
    - composer test

after_script:
    - composer coveralls