version: '3.7'

services:
    postgres:
        image: postgres:11.7
        networks:
            - default
        volumes:
            - ./vendor/prooph/pdo-event-store/scripts/postgres/01_event_streams_table.sql:/docker-entrypoint-initdb.d/01_event_streams_table.sql
        environment:
            - POSTGRES_DB=eventstore
            - POSTGRES_USER=eventstore
            - POSTGRES_PASSWORD=eventstore123
        ports:
            - 5432:5432
    mysql:
        image: mysql:5.7
        networks:
            - default
        volumes:
            - ./vendor/prooph/pdo-event-store/scripts/mysql/01_event_streams_table.sql:/docker-entrypoint-initdb.d/01_event_streams_table.sql
        environment:
            - MYSQL_DATABASE=eventstore
            - MYSQL_USER=eventstore
            - MYSQL_PASSWORD=eventstore123
            - MYSQL_ROOT_PASSWORD=eventstore123
        ports:
            - 3306:3306