name: "Tests"

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:

        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                php:
                    - "7.4"
                    - "8.0"
                os:
                    - "ubuntu-latest"

        steps:
            -   name: "Checkout"
                uses: actions/checkout@v2

            -   name: "Install PHP"
                uses: "shivammathur/setup-php@v2"
                with:
                    coverage: pcov
                    tools: composer:v2
                    php-version: "${{ matrix.php }}"
                    ini-values: memory_limit=-1

            -   name: "Cache dependencies"
                uses: "actions/cache@v2"
                with:
                    path: |
                        ~/.composer/cache
                        vendor
                    key: "php-${{ matrix.php }}-${{ matrix.os }}"
                    restore-keys: "php-${{ matrix.php }}-${{ matrix.os }}"

            -   name: "Require php-coveralls/php-coveralls"
                run: "composer global require php-coveralls/php-coveralls"

            -   name: "Install dependencies"
                run: "composer update -n --prefer-dist"

            -   name: "Testing"
                run: "composer test"

            -   name: "Upload coverage results to Coveralls"
                env:
                    COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                run: "php-coveralls -v"
